### ISSUE TITLE
Enable media autoplay in firefox

### ISSUE THREAD

**Issue by iFrederic** [Jet0JLH/piScreen#3]
Please enable autoplay in firefox by default. Use the firefox config "media.autoplay.default" and set it to "0" to enable autoplay. 

**media.autoplay.default**
> An integer preference which specifies whether per-domain configuration for autoplay support by default is allowed (0), blocked (1), or prompt-on-use (2). The default value is 0.

**Comment by Jet0JLH** [comment]
Feature added in commit 0a205bc
The feature will be available in the next release.
